//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int Id { get; set; }
        public string Account_number { get; set; }
        public string AccountType { get; set; }
        public decimal Amount { get; set; }
        public bool IsClosed { get; set; }
        public int PersonId { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
